export const WeatherType = {
    ExtraSunny: 0,
    Clear: 1,
    Clouds: 2,
    Smog: 3,
    Foggy: 4,
    Overcast: 5,
    Rain: 6,
    Thunder: 7,
    Clearing: 8,
    Neutral: 9,
    Snow: 10,
    Blizzard: 11,
    Snowlight: 12,
    Xmas: 13,
    Halloween: 14,
};
