export const defaultData = {
    parentData: {
        motherIndex: 0,
        fatherIndex: 0,
        motherID: 21,
        fatherID: 0,
        resemblance: 50,
        skintone: 50,
    },
    hairData: {
        hairIndex: 0,
        hairID: 0,
        facialHairIndex: 0,
        facialHairOpacity: 100,
        chestHairIndex: 0,
        chestHairOpacity: 100,
        hairColor: 0,
        highlightColor: 0,
        facialHairColor: 0,
        chestHairColor: 0,
    },
    eyesData: {
        eyeIndex: 0,
        eyebrowsIndex: 0,
        eyebrowsOpacity: 100,
        eyebrowsColor: 0,
    },
    featureValue: ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
    appearanceValue: [
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
        { index: 0, opacity: 100, color: 0 },
    ],
    equipment: {
        hats: [-1, 0, 'Default'],
        glasses: [-1, 0, 'Default'],
        watches: [-1, 0, 'Default'],
        ears: [-1, 0, 'Default'],
        bracelets: [-1, 0, 'Default'],
        tops: [-1, 0, 0, 0, 'Default'],
        pants: [-1, 0, 'Default'],
        shoes: [-1, 0, 'Default'],
        masks: [-1, 0, 'Default'],
        ties: [-1, 0, 'Default'],
        bags: [-1, 0, 'Default'],
        armours: [-1, 0, 'Default'],
    },
};
